apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: taskforge-auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/taskforge-auth
        - name: JWT_SECRET
          value: taskforge-super-secret-key

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
