name: TaskForge CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Auth Dependencies
        run: |
          cd services/auth-service
          npm install

  build-task-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Task Dependencies
        run: |
          cd services/task-service
          npm install

  build-notification-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Notification Dependencies
        run: |
          cd services/notification-service
          npm install

  build-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Gateway Dependencies
        run: |
          cd services/api-gateway
          npm install
