name: TaskForge CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-auth-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd services/auth-service
          npm install

      - run: |
          docker build -t auth-service ./services/auth-service

  build-task-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd services/task-service
          npm install

      - run: |
          docker build -t task-service ./services/task-service

  build-notification-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd services/notification-service
          npm install

      - run: |
          docker build -t notification-service ./services/notification-service

  build-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          cd services/api-gateway
          npm install

      - run: |
          docker build -t api-gateway ./services/api-gateway
